# adapted from https://github.com/khezen/compose-postgres/tree/master
# version: "3"
services:
  postgres:
    container_name: service_search_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-pgadmin}
      POSTGRES_PASSWORD: ${DB_PASS:-changeme}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
        postgres:
          ipv4_address: 10.103.0.2
    restart: unless-stopped

  pgadmin:
    container_name: service_search_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16

volumes:
  postgres:
  pgadmin:
